# Generated by Django 5.1 on 2024-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='telegram_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
