# Generated by Django 5.1 on 2024-08-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_group_telegram_id_group_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionrequest',
            old_name='user_id',
            new_name='user_telegram_id',
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Declined'), (4, 'Completed')], default=1),
        ),
    ]
