# Generated by Django 5.1 on 2024-09-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_subscriptionrequest_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
