# Generated by Django 5.1 on 2024-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_subscriptionrequest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_removed_from_group_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
