# Generated by Django 5.1 on 2024-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_user_last_removed_from_group_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_added_to_group_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
