# Generated by Django 5.1 on 2024-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_user_last_added_to_group_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
