# Generated by Django 5.1 on 2024-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_subscriptionrequest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tradingview_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='tradingview_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
