# Generated by Django 5.1 on 2024-11-02 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_subscription_tradingview_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.group'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('salla', 'سلة'), ('stc', 'STC'), ('trial', 'تجربة مجانيه'), ('other', 'أخرى')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='payment_method',
            field=models.CharField(choices=[('salla', 'سلة'), ('stc', 'STC'), ('trial', 'تجربة مجانيه'), ('other', 'أخرى')], max_length=50),
        ),
    ]
