# Generated by Django 5.1 on 2024-11-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_group_parent_alter_subscription_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.group', to_field='telegram_id'),
        ),
        migrations.AlterField(
            model_name='group',
            name='telegram_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
