# Generated by Django 5.1 on 2024-11-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_group_parent_alter_group_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='message',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
