# Generated by Django 5.1 on 2024-11-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_subscriptionrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('tutor', 'Tutor')], max_length=30),
        ),
    ]
