# Generated by Django 5.1 on 2024-11-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='invoice_number',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='training',
            name='payment_method',
            field=models.CharField(choices=[('salla', 'سلة'), ('stc', 'STC'), ('trial', 'تجربة مجانيه'), ('other', 'أخرى')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='training',
            name='couch_telegram',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.employee'),
        ),
    ]
