# Generated by Django 5.1 on 2024-11-14 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_training_invoice_number_training_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 11, 14)),
        ),
        migrations.AddField(
            model_name='training',
            name='message',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='training',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
