# Generated by Django 5.1 on 2024-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_training_created_at_training_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='anounced',
            field=models.BooleanField(default=False),
        ),
    ]
