# Generated by Django 5.1 on 2024-11-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_subscriptionrequest_anounced_training_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='have_task',
            field=models.BooleanField(default=False),
        ),
    ]
