# Generated by Django 5.1 on 2024-11-18 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_employee_have_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 11, 18)),
        ),
        migrations.AlterField(
            model_name='training',
            name='invoice_number',
            field=models.CharField(default='free trial', max_length=300),
        ),
    ]
