# Generated by Django 5.1 on 2024-12-07 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_training_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('telegram_username', models.CharField(max_length=255)),
                ('review', models.IntegerField(choices=[(0, 'Very Bad'), (1, 'Bad'), (2, 'Okay'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('message', models.CharField(default=False, max_length=255)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='invoice_number',
            field=models.CharField(default='free trial', max_length=200),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 12, 7)),
        ),
    ]
