# Generated by Django 5.1 on 2024-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_feedback_alter_subscriptionrequest_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
