# Generated by Django 5.1 on 2024-12-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='renew',
            field=models.BooleanField(default=False),
        ),
    ]
