# Generated by Django 5.1 on 2024-12-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_subscriptionrequest_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewed',
            field=models.BooleanField(default=False),
        ),
    ]
